name: compact_pay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  device_preview: ^1.1.0
  google_fonts: ^3.0.1
  email_otp: ^1.0.4
  timer_count_down: ^2.2.1
  smooth_page_indicator: ^1.0.0+2
  progress_dialog: ^1.2.4
  #  //intl: ^0.18.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  pin_code_fields: ^7.4.0
  dio: ^4.0.6
  grouped_list: ^5.1.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

#dependency_overrides:
#  firebase_core_platform_interface: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


